### ISSUE TITLE
Could not open extension control file

### ISSUE THREAD

**Issue by sollevix67** [VoidRunner87/mydu_pve_mod#8]
Found an issue that cause the container to crash, this after running `docker-compose pull` :

```
24-10-18 21:37:05 could parse config file at '../config/dual.yaml'
2024-10-18 21:37:05 Queuing URL: http://queueing:9630
2024-10-18 21:37:05 configuring log system from ../config/dual.yaml console: Error
2024-10-18 21:37:05 will log to '/logs/Mod.json'
2024-10-18 21:37:05 will log to '/logs/Mod.log'
2024-10-18 21:37:08 Starting Services V2
2024-10-18 21:37:08 StartServicesV2
2024-10-18 21:37:08 Starting NQutils.InitializerService`1[Backend.IGameplayBank]
2024-10-18 21:37:13 Starting NQ.Router.ClusterClientService
2024-10-18 21:37:13 Starting NQutils.InitializerService`1[Backend.IUserContent]
2024-10-18 21:37:14 Starting NQutils.InitializerService`1[Backend.IVoxelService]
2024-10-18 21:37:14 Starting NQutils.InitializerService`1[Backend.IVoxelImporter]
2024-10-18 21:37:14 Starting NQutils.InitializerService`1[NQutils.Sql.ISql]
2024-10-18 21:37:14 Starting NQutils.InitializerService`1[Backend.IRDMSStorage]
2024-10-18 21:37:14 Starting NQutils.InitializerService`1[Backend.IPlanetList]
2024-10-18 21:37:14 Starting NQutils.InitializerService`1[Backend.Scenegraph.IScenegraph]
2024-10-18 21:37:14 Starting NQutils.InitializerService`1[Backend.IPub]
2024-10-18 21:37:14 Starting NQutils.InitializerService`1[NQ.Visibility.Internal+InternalClient]
2024-10-18 21:37:14 Starting NQutils.InitializerService`1[Backend.Scenegraph.IScenegraphAPI]
2024-10-18 21:37:15 Services Started
2024-10-18 21:37:15 Creating BOT User
2024-10-18 21:37:15 Waiting in Queue
2024-10-18 21:37:19 Empty
2024-10-18 21:37:19 Empty
2024-10-18 21:37:19 Default
2024-10-18 21:37:19 Empty
2024-10-18 21:37:19 Empty
2024-10-18 21:37:19 Empty
2024-10-18 21:37:19 Default
2024-10-18 21:37:19 GRPC Info 2: 88.198.102.60:9210
2024-10-18 21:37:19 Connection: 10.5.0.5:9210
2024-10-18 21:37:19 Connection GPRC: 10.5.0.5:9210
2024-10-18 21:37:19 Connection FRONT: queueing:9630
2024-10-18 21:37:20 OLD Item Bank URL NOT CREATION: https://du-queueing.sollevix.ovh/public/itembank/serialized/aa44839d361d6b5199bca1128531ca5c7e4ae8a03d02163c3a8b6bf7e704ee6a
2024-10-18 21:37:20 OVERRIDE Item Bank URL NOT CREATION: https://du-queueing.sollevix.ovh/public/itembank/serialized/aa44839d361d6b5199bca1128531ca5c7e4ae8a03d02163c3a8b6bf7e704ee6a
2024-10-18 21:37:24 BOT User Created
2024-10-18 21:37:24 configuring log system from ../config/dual.yaml console: Error
2024-10-18 21:37:24 will log to '/logs/Mod.json'
2024-10-18 21:37:24 will log to '/logs/Mod.log'
2024-10-18 21:37:24 Executing DB Migrations
2024-10-18 21:37:25 System.ObjectDisposedException: NpgsqlTransaction
2024-10-18 21:37:25  ---> Npgsql.PostgresException (0x80004005): 58P01: could not open extension control file "/usr/share/postgresql/11/extension/postgis.control": No such file or directory
2024-10-18 21:37:25    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|223_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
2024-10-18 21:37:25    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
2024-10-18 21:37:25    at Npgsql.NpgsqlDataReader.NextResult()
2024-10-18 21:37:25    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
2024-10-18 21:37:25    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
2024-10-18 21:37:25    at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
2024-10-18 21:37:25    at Npgsql.NpgsqlCommand.ExecuteNonQuery()
2024-10-18 21:37:25    at FluentMigrator.Runner.Processors.Postgres.PostgresProcessor.Process(String sql)
2024-10-18 21:37:25   Exception data:
2024-10-18 21:37:25     Severity: ERROR
2024-10-18 21:37:25     SqlState: 58P01
2024-10-18 21:37:25     MessageText: could not open extension control file "/usr/share/postgresql/11/extension/postgis.control": No such file or directory
2024-10-18 21:37:25     File: extension.c
2024-10-18 21:37:25     Line: 494
2024-10-18 21:37:25     Routine: parse_extension_control_file
2024-10-18 21:37:25    --- End of inner exception stack trace ---
2024-10-18 21:37:25    at Npgsql.NpgsqlTransaction.CheckDisposed()
2024-10-18 21:37:25    at Npgsql.NpgsqlTransaction.CheckReady()
2024-10-18 21:37:25    at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
2024-10-18 21:37:25    at Npgsql.NpgsqlTransaction.Rollback()
2024-10-18 21:37:25    at FluentMigrator.Runner.Processors.GenericProcessorBase.RollbackTransaction()
2024-10-18 21:37:25    at FluentMigrator.Runner.Processors.GenericProcessorBase.Dispose(Boolean isDisposing)
2024-10-18 21:37:25    at FluentMigrator.Runner.Processors.ProcessorBase.Dispose()
2024-10-18 21:37:25    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
2024-10-18 21:37:25    at Mod.DynamicEncounters.Program.Main(String[] args) in /src/Program.cs:line 64
2024-10-18 21:37:25 Unhandled exception. System.ObjectDisposedException: NpgsqlTransaction
2024-10-18 21:37:25  ---> Npgsql.PostgresException (0x80004005): 58P01: could not open extension control file "/usr/share/postgresql/11/extension/postgis.control": No such file or directory
2024-10-18 21:37:25    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|223_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
2024-10-18 21:37:25    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
2024-10-18 21:37:25    at Npgsql.NpgsqlDataReader.NextResult()
2024-10-18 21:37:25    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
2024-10-18 21:37:25    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
2024-10-18 21:37:25    at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
2024-10-18 21:37:25    at Npgsql.NpgsqlCommand.ExecuteNonQuery()
2024-10-18 21:37:25    at FluentMigrator.Runner.Processors.Postgres.PostgresProcessor.Process(String sql)
2024-10-18 21:37:25   Exception data:
2024-10-18 21:37:25     Severity: ERROR
2024-10-18 21:37:25     SqlState: 58P01
2024-10-18 21:37:25     MessageText: could not open extension control file "/usr/share/postgresql/11/extension/postgis.control": No such file or directory
2024-10-18 21:37:25     File: extension.c
2024-10-18 21:37:25     Line: 494
2024-10-18 21:37:25     Routine: parse_extension_control_file
2024-10-18 21:37:25    --- End of inner exception stack trace ---
2024-10-18 21:37:25    at Npgsql.NpgsqlTransaction.CheckDisposed()
2024-10-18 21:37:25    at Npgsql.NpgsqlTransaction.CheckReady()
2024-10-18 21:37:25    at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
2024-10-18 21:37:25    at Npgsql.NpgsqlTransaction.Rollback()
2024-10-18 21:37:25    at FluentMigrator.Runner.Processors.GenericProcessorBase.RollbackTransaction()
2024-10-18 21:37:25    at FluentMigrator.Runner.Processors.GenericProcessorBase.Dispose(Boolean isDisposing)
2024-10-18 21:37:25    at FluentMigrator.Runner.Processors.ProcessorBase.Dispose()
2024-10-18 21:37:25    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
2024-10-18 21:37:25    at Mod.DynamicEncounters.Program.Main(String[] args) in /src/Program.cs:line 64
2024-10-18 21:37:25    at Mod.DynamicEncounters.Program.<Main>(String[] args)
```

**Comment by VoidRunner87** [comment]
This looks like some issue on your postgress instance. Not the mod.

**Comment by VoidRunner87** [comment]
Actually what this might be is that a new step on the readme was added mentioning to replace the postgres instance with:
```
postgres:
    image: postgis/postgis:11-3.3
```

The mod now uses geo-spatial algorithms and querying from postgis for more performant spatial querying.

**Comment by VoidRunner87** [comment]
Closing this for now. Reopen if that's not it and if it's mod related and not your instance of the DB-related.
